# Generated by Django 2.2.1 on 2019-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('name', models.CharField(max_length=50, verbose_name='Cliente')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('city', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
    ]
