# Generated by Django 2.2.1 on 2019-05-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('loan', '0003_auto_20190520_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Company', verbose_name='Compañia'),
        ),
    ]
