# Generated by Django 2.2.1 on 2019-05-21 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
    ]
