# Generated by Django 2.2.1 on 2019-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190520_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Código de Factura'),
        ),
    ]
