# Generated by Django 2.2.1 on 2019-05-21 15:10

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190520_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, default=invoice.models.increment_invoice_number, max_length=500, null=True, verbose_name='Código de Factura'),
        ),
    ]
